### ISSUE TITLE
License and copyright information of test data

### ISSUE THREAD

**Issue by ViviCoder** [michelp/mmparse#2]
What is the license and copyright information of the matrix files used for testing?

**Comment by michelp** [comment]
To my knowledge the matrix market collection data itself is public domain.  The website has some citation recommendations:
https://sparse.tamu.edu/about

**Comment by ViviCoder** [comment]
I would like to package `pygraphblas` for Debian, which requires packaging its dependencies.
This includes `mmparse`.

Debian is pretty strict about license and copyright, so if the test matrices are public domain, this should be written somewhere.

**Comment by michelp** [comment]
@DrTimothyAldenDavis do you know more about the explicit licensing about shipping matrix market files?

**Comment by DrTimothyAldenDavis** [comment]
I've added a clarification and a license for the data itself:  CC-BY 4.0.  See https://github.com/ScottKolo/suitesparse-matrix-collection-website#license .  That will also appear at http://sparse.tamu.edu/about once the site is updated.

**Comment by michelp** [comment]
Thanks Tim!
